services:
  mysql:
    image: mysql:latest
    container_name: mysql-order
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dostoevsky2324
      MYSQL_DATABASE: order_service
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql #initialize db with init.sql

